 CREATE TABLE PRODUCTS(
     PRODUCT_ID INT IDENTITY(1,1),
     NAME VARCHAR(60) NOT NULL,
     SPECIFICATION VARCHAR(255) NOT NULL,
     QUANTITY FLOAT,
     COLOR VARCHAR(30) NOT NULL,
     REGISTRATION_DATE DATETIME,
     STATUS VARCHAR(11) NOT NULL
     
     PRIMARY KEY(PRODUCT_ID)
);